### ISSUE TITLE
Borders change color

### ISSUE THREAD

**Issue by joto** [GIScience/ohsome-dashboard#5]
When I zoom in some borders change color in some zoom levels in weird ways. Maybe that is intentional to show different `admin_level`s in different colors? It is rather confusing, especially when during loading you see some tiles from the higher zoom levels and some from the lower at the same time.

**Comment by mcauer** [comment]
Thanks for sharing your experience.

admin levels are a quite complex topic. The same level varies quite a lot in sizes and often some admin levels do not exist in every country. To avoid empty unclickable spaces we mix admin_levels in the same zoomlevel if there is no corresponding admin level available. E.g. some Bundesländer (4) do have Regierungsbezierke (5) others don't and switch directly to Kreise(6). If we only would show one admin_level per zoomlevel at a time, large parts of germany would be unclickable in that zoomlevel.

I think a legend could also help to reduce confusion.

**Comment by mcauer** [comment]
The following example shows that 
- Luxemburg (2) has no Level 3, no Bundesländer (4) nor (Regierungsbezierke (5).
- Rhineland-Palatinate(4) has no Regierungsbezirke (5)
- But Baden-Württemberg, NRW, Hessen do have Regierungsbezirke (5)

So we see level 2, 4 and 5 in the same zoomlevel. One zoomlevel further in switches all of them to Kreislevel (6) because this is available for all of them.

![image](https://github.com/GIScience/ohsome-dashboard/assets/2814068/7d68edff-25ab-4d77-8f07-ab202d7c9162)
